# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'PromiseKit', '~> 6.0'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'Kingfisher'
  pod 'SnapKit', '~> 4.0.0'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyBeaver'
  pod 'SDWebImage'
  pod 'Alamofire-SwiftyJSON'
  pod 'Pageboy'
  pod 'SwiftKeychainWrapper'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'IQKeyboardManagerSwift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Socket.IO-Client-Swift' , '12.1.2'
  pod 'SlackTextViewController'
  pod 'LoremIpsum'
  pod 'GooglePlacePicker'
  pod 'Toaster'
  pod 'UIImageView-Letters'
  pod 'SwiftLocation', '~> 3.2.3'
#  pod 'FLAnimatedImage'
  pod 'AXPhotoViewer'
  pod 'CLImageEditor/AllTools'
#  pod 'Firebase/Core'
#  pod 'Firebase/Messaging'
  pod 'NVActivityIndicatorView'
  pod 'SwiftMessages'
#  pod 'PayPal-iOS-SDK'
#  pod 'Hero'
#  pod 'SkeletonView'
#  pod 'ViewAnimator'
#  pod 'SwipeCellKit'
#  pod 'Spruce', '~> 1.0.0'
#  pod 'BulletinBoard'
#  pod 'TinyConstraints'
#  pod 'Gemini'
#  pod 'MessageKit'
#  pod 'CollectionKit'
#  pod 'HGPlaceholders'
#  pod 'DefaultsKit'
#  pod 'TimeIntervals', '~> 1.0.0'
#  pod 'Material', '~> 2.0'

end
