//
//  BookmarkInteractor.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookmarkBusinessLogic
{
  func doSomething(request: Bookmark.Something.Request)
}

protocol BookmarkDataStore
{
  //var name: String { get set }
}

class BookmarkInteractor: BookmarkBusinessLogic, BookmarkDataStore
{
  var presenter: BookmarkPresentationLogic?
  var worker: BookmarkWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Bookmark.Something.Request)
  {
    worker = BookmarkWorker()
    worker?.doSomeWork()
    
    let response = Bookmark.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
