//
//  BookmarkViewController.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookmarkDisplayLogic: class
{
  func displaySomething(viewModel: Bookmark.Something.ViewModel)
}

class BookmarkViewController: UIViewController, BookmarkDisplayLogic
{
  var interactor: BookmarkBusinessLogic?
  var router: (NSObjectProtocol & BookmarkRoutingLogic & BookmarkDataPassing)?

  // MARK: Object lifecycle
  
    override func loadView() {
        super.loadView()
        setup()
        initView()
    }
    private func initView() {
        view = MView()
    }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = BookmarkInteractor()
    let presenter = BookmarkPresenter()
    let router = BookmarkRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Bookmark.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Bookmark.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
