//
//  BusinessPresenter.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BusinessPresentationLogic
{
  func presentSomething(response: Business.Something.Response)
}

class BusinessPresenter: BusinessPresentationLogic
{
  weak var viewController: BusinessDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Business.Something.Response)
  {
    let viewModel = Business.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
