//
//  BusinessInteractor.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BusinessBusinessLogic
{
  func doSomething(request: Business.Something.Request)
}

protocol BusinessDataStore
{
  //var name: String { get set }
}

class BusinessInteractor: BusinessBusinessLogic, BusinessDataStore
{
  var presenter: BusinessPresentationLogic?
  var worker: BusinessWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Business.Something.Request)
  {
    worker = BusinessWorker()
    worker?.doSomeWork()
    
    let response = Business.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
