//
//  MainViewController.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainDisplayLogic: class
{
    func displaySomething(viewModel: Main.Something.ViewModel)
}

class MainViewController: UITabBarController, MainDisplayLogic
{
    var interactor: MainBusinessLogic?
    var router: (NSObjectProtocol & MainRoutingLogic & MainDataPassing)?
    
    // MARK: Object lifecycle
    override func loadView() {
        super.loadView()
        setup()
        initView()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MainInteractor()
        let presenter = MainPresenter()
        let router = MainRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func initView() {
        // business tab
        let businessTab = BusinessViewController()
        let businessBarItem = K.UI.TabBar.creatTabBarItem(title: nil, image: #imageLiteral(resourceName: "ic_home_outline"), selectedImage: #imageLiteral(resourceName: "ic_home"))
        businessTab.tabBarItem = businessBarItem
        
        // chat tab
        let chatTab = ChatViewController()
        let chatBarItem = K.UI.TabBar.creatTabBarItem(title: nil, image: #imageLiteral(resourceName: "ic_chats_outline"), selectedImage: #imageLiteral(resourceName: "ic_chats"))
        chatTab.tabBarItem = chatBarItem
        
        // bookmarks tab
        let bookmarksTab = BookmarkViewController()
        let bookmarksBarItem = K.UI.TabBar.creatTabBarItem(title: nil, image: #imageLiteral(resourceName: "ic_bookmarks_outline"), selectedImage: #imageLiteral(resourceName: "ic_bookmarks"))
        bookmarksTab.tabBarItem = bookmarksBarItem
        
        // feed tab
        let feedTab = FeedViewController()
        let feedBarItem = K.UI.TabBar.creatTabBarItem(title: nil, image: #imageLiteral(resourceName: "ic_feed_outline"), selectedImage: #imageLiteral(resourceName: "ic_feed"))
        feedTab.tabBarItem = feedBarItem
        
        // profile
        let profileTab = ProfileViewController()
        let profileBarItem = K.UI.TabBar.creatTabBarItem(title: nil, image: #imageLiteral(resourceName: "ic_profile_outline"), selectedImage: #imageLiteral(resourceName: "ic_profile"))
        profileTab.tabBarItem = profileBarItem
        
        K.UI.TabBar.configTabBar(self.tabBar)
        self.viewControllers = [businessTab, chatTab, bookmarksTab, feedTab, profileTab]
    }
    
    // MARK: UITabBarControllerDelegate method
    
    func tabBarController(_ tabBarController: UITabBarController, didSelectViewController viewController: UIViewController) {
        print("Selected \(viewController.title!)")
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Main.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Main.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
