//
//  FeedInteractor.swift
//  App
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedBusinessLogic
{
  func doSomething(request: Feed.Something.Request)
}

protocol FeedDataStore
{
  //var name: String { get set }
}

class FeedInteractor: FeedBusinessLogic, FeedDataStore
{
  var presenter: FeedPresentationLogic?
  var worker: FeedWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Feed.Something.Request)
  {
    worker = FeedWorker()
    worker?.doSomeWork()
    
    let response = Feed.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
