//
//  LoginRouter.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToMain()
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Route
  func routeToMain() {
    guard let source = self.viewController else { return }
    let mainVC = MainViewController()
    navigateToMain(source: source, destination: mainVC)
//    passDataToMain(source: dataStore, destination: &businessVC)
  }

  // MARK: Navigation
  func navigateToMain(source: LoginViewController, destination: MainViewController)
  {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  //   MARK: Passing data
  func passDataToMain(source: LoginDataStore?, destination: inout BusinessViewController)
  {
    //    destination.name = source.name
  }
}
