//
//  LoginWorker.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

//typealias responseHandler = (_ response:TestModel.Fetch.Response) ->()
//
//class TestWorker{
//
//    func fetch(itemId:Int!, keyword:String!, count: String!, success:@escaping(responseHandler), fail:@escaping(responseHandler))
//    {
//        // NOTE: Do the work
//        //call network etc.
//        let manager = YourApiManager()
//
//        manager.fetch(itemId: itemId, keyword: keyword, count: count, success: { (data) in
//            let test = Test(JSON: data)
//            success(TestModel.Fetch.Response(testObj: test, isError: false, message:nil))
//        }) { (error, message) in
//            fail(TestModel.Fetch.Response(testObj: nil, isError: true, message: message))
//        }
//    }
//}

class LoginWorker
{
    func login(email: String, password: String) -> Promise<LoginResult>
    {
        return ApiService.shared.login(email: email, password: password)
    }
}
