//
//  LoginInteractor.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

protocol LoginBusinessLogic
{
    func login(request: Login.Login.Request)
}

protocol LoginDataStore
{
    //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func login(request: Login.Login.Request)
    {
        worker = LoginWorker()
        worker?.login(email: request.email, password: request.password)
            .done({ (result) in
                LocalStorageService.shared.saveToken(token: result.token)
                ApiService.shared.setToken(result.token)
                let response = Login.Login.Response(LoginResult: result, isError: false, errorMessage: nil)
                self.presenter?.presentLoginResult(response: response)
            })
            .catch({ (error) in
                let response = Login.Login.Response(LoginResult: nil, isError: true, errorMessage: error.localizedDescription)
                self.presenter?.presentLoginResult(response: response)
            })
    }
}
