//
//  LoginPresenter.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func showLoading(response: Login.ShowLoading.Response)
    func hideLoading(response: Login.HideLoading.Response)
    func showError(response: Login.ShowError.Response)
    func gotoMain(response: Login.GotoMain.Response)
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    func showLoading(response: Login.ShowLoading.Response) {
        viewController?.showLoading(viewModel: Login.ShowLoading.ViewModel())
    }
    
    func hideLoading(response: Login.HideLoading.Response) {
        viewController?.hideLoading(viewModel: Login.HideLoading.ViewModel())
    }
    
    // MARK: Do something
    func showError(response: Login.ShowError.Response) {
        let viewModel = Login.ShowError.ViewModel(errorString: response.error.localizedDescription)
        viewController?.displayError(viewModel: viewModel)
    }
    
    func gotoMain(response: Login.GotoMain.Response) {
        viewController?.gotoMain(viewModel: Login.GotoMain.ViewModel())
    }
}
