//
//  LoginPresenter.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
  func presentLoginResult(response: Login.Login.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  func presentLoginResult(response: Login.Login.Response) {
    let viewModel = Login.Login.ViewModel(token: response.LoginResult?.token, isError: response.isError, errorMessage: response.errorMessage)
    viewController?.displayLoginResult(viewModel: viewModel)
  }
}
