//
//  LoginModels.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum Login
    {
        struct Request {
            var email: String
            var password: String
        }
        
        struct Response
        {
            var token: String?
            var isSuccess: Bool
            var error: Error?
        }
        
        struct ViewModel {
            var isSuccess: Bool
            var errorString: String?
        }
    }
    
    enum GotoMain {
        struct Request {}
        struct Response{}
        struct ViewModel{}
    }
    
    enum ShowError {
        struct Request {}
        struct Response{
            var error: Error
        }
        struct ViewModel{
            var errorString: String
        }
    }
    
    enum ShowLoading {
        struct Request {}
        struct Response{}
        struct ViewModel{}
    }
    
    enum HideLoading {
        struct Request {}
        struct Response{}        
        struct ViewModel{}
    }
}
