//
//  LoginModels.swift
//  CleanSwift
//
//  Created by Ha Linh on 9/5/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
        var email: String
        var password: String
    }
    
    struct Response
    {
        var LoginResult: LoginResult?
        var isError: Bool
        var errorMessage: String?
    }
    
    struct ViewModel
    {
        var token: String?
        var isError: Bool
        var errorMessage: String?
    }
  }
}
