//
//  LaunchViewController.swift
//  YouBChat
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol LaunchDisplayLogic: class
{
    func routeToNextScene(viewModel: Launch.AutoLogin.ViewModel)
}

class LaunchViewController: UIViewController, LaunchDisplayLogic
{
    var interactor: LaunchBusinessLogic?
    var router: (NSObjectProtocol & LaunchRoutingLogic & LaunchDataPassing)?
    
    // MARK: Object lifecycle
    
    override func loadView() {
        super.loadView()
        setup()
        initView()
    }
    
    var labelLoading: MLabel!
    
    private func initView() {
        view = MView()
        
        labelLoading = MLabel()
        view.addSubview(labelLoading)
        labelLoading.text = "Loading ..."
        labelLoading.snp.makeConstraints { (m) in
            m.centerX.centerY.equalToSuperview()
        }
        
        
    }
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LaunchInteractor()
        let presenter = LaunchPresenter()
        let router = LaunchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        autoLogin()
    }
    
    // MARK: Do something
    
    func autoLogin()
    {
        let request = Launch.AutoLogin.Request()
        interactor?.autoLogin(request: request)
    }
    
    // MARK: Display someting
    func routeToNextScene(viewModel: Launch.AutoLogin.ViewModel)
    {
        if viewModel.autoLoginSuccess {
            router?.routeToMain()
        } else {
            router?.routeToLogin()
        }
    }
}
