//
//  LaunchPresenter.swift
//  YouBChat
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LaunchPresentationLogic
{
  func goToNextScene(response: Launch.AutoLogin.Response)
}

class LaunchPresenter: LaunchPresentationLogic
{
  weak var viewController: LaunchDisplayLogic?
  
  // MARK: Do something
  
  func goToNextScene(response: Launch.AutoLogin.Response)
  {
    let viewModel = Launch.AutoLogin.ViewModel(autoLoginSuccess: response.autoLoginSuccess)
    viewController?.routeToNextScene(viewModel: viewModel)
  }
}
