//
//  LaunchRouter.swift
//  YouBChat
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LaunchRoutingLogic
{
    func routeToLogin()
    func routeToMain()
}

protocol LaunchDataPassing
{
    var dataStore: LaunchDataStore? { get }
}

class LaunchRouter: NSObject, LaunchRoutingLogic, LaunchDataPassing
{
    weak var viewController: LaunchViewController?
    var dataStore: LaunchDataStore?
    
    // MARK: Routing
    
    func routeToLogin()
    {
        let loginVC = LoginViewController()
        viewController?.navigationController?.pushViewController(loginVC, animated: true)
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
        
    }
    
    func routeToMain() {
        let mainVC = MainViewController()
        viewController?.navigationController?.pushViewController(mainVC, animated: true)

    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: LaunchViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: LaunchDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
