//
//  LaunchInteractor.swift
//  YouBChat
//
//  Created by Ha Linh on 9/10/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LaunchBusinessLogic
{
  func autoLogin(request: Launch.AutoLogin.Request)
}

protocol LaunchDataStore
{
  //var name: String { get set }
}

class LaunchInteractor: LaunchBusinessLogic, LaunchDataStore
{
  var presenter: LaunchPresentationLogic?
  var worker: LaunchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func autoLogin(request: Launch.AutoLogin.Request)
  {
    worker = LaunchWorker()
    if let savedToken = worker?.getSaveToken() {
        ApiService.shared.setToken(savedToken)
        let response = Launch.AutoLogin.Response(autoLoginSuccess: true)
        presenter?.goToNextScene(response: response)
    } else {
        let response = Launch.AutoLogin.Response(autoLoginSuccess: false)
        presenter?.goToNextScene(response: response)

    }
  }
}
