//
//  LogoutWorker.swift
//  App
//
//  Created by Ha Linh on 12/21/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LogoutWorker
{
  func doSomeWork()
  {
  }
}
