//
//  LogoutViewController.swift
//  App
//
//  Created by Ha Linh on 12/21/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogoutDisplayLogic: class
{
  func displaySomething(viewModel: Logout.Something.ViewModel)
}

class LogoutViewController: UIViewController, LogoutDisplayLogic
{
  var interactor: LogoutBusinessLogic?
  var router: (NSObjectProtocol & LogoutRoutingLogic & LogoutDataPassing)?

  // MARK: Object lifecycle
  override func loadView() {
    super.loadView()
    setup()
    initView()
  }
  
  // MARK: Setup
  private func setup()
  {
    let viewController = self
    let interactor = LogoutInteractor()
    let presenter = LogoutPresenter()
    let router = LogoutRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }

  // MARK: Init View
  private func initView() {
  
  }

  // MARK: View lifecycle
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something  
  func doSomething()
  {
    let request = Logout.Something.Request()
    interactor?.doSomething(request: request)
  }
  // MARK: Display something
  func displaySomething(viewModel: Logout.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
