//
//  LogoutRouter.swift
//  App
//
//  Created by Ha Linh on 12/21/18.
//  Copyright (c) 2018 HaLinh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogoutRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LogoutDataPassing
{
  var dataStore: LogoutDataStore? { get }
}

class LogoutRouter: NSObject, LogoutRoutingLogic, LogoutDataPassing
{
  weak var viewController: LogoutViewController?
  var dataStore: LogoutDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
    // 
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LogoutViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LogoutDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
